In [22]:
def get_selected_features(X, X_new):
    selected_features= []
    for i in range(len(X_new.columns)):
        for j in range(len(X.columns)):
            if (X_new.iloc[:,i].equals(X.iloc[:,j])):
                print(X.columns[j])
                selected_features.append(X.columns[j])
    return selected_features

In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [3]:
df = pd.read_csv('../datasets/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
X = df.drop('Outcome', axis=1).astype(np.float64)
Y = df['Outcome']

In [16]:
fit = SelectKBest(score_func=chi2, k=4).fit(X, Y)

In [18]:
fit.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [19]:
X_new = fit.transform(X)

In [20]:
X_new

array([[148. ,   0. ,  33.6,  50. ],
       [ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

In [24]:
X_new = pd.DataFrame(X_new)

In [27]:
selected_features = get_selected_features(X, X_new)

Glucose
Insulin
BMI
Age


In [28]:
chi2_features = X[selected_features]

In [29]:
chi2_features.head()

Glucose  Insulin   BMI   Age
0    148.0      0.0  33.6  50.0
1     85.0      0.0  26.6  31.0
2    183.0      0.0  23.3  32.0
3     89.0     94.0  28.1  21.0
4    137.0    168.0  43.1  33.0

In [30]:
from sklearn.feature_selection import f_classif, SelectPercentile

In [38]:
fit = SelectPercentile(f_classif, percentile=80).fit(X, Y)

In [39]:
fit.scores_

array([ 39.67022739, 213.16175218,   3.2569504 ,   4.30438091,
        13.28110753,  71.7720721 ,  23.8713002 ,  46.14061124])

In [40]:
X_new = fit.transform(X)

In [41]:
X_new = pd.DataFrame(X_new)

In [42]:
X_new.head()

0      1      2     3      4     5
0  6.0  148.0    0.0  33.6  0.627  50.0
1  1.0   85.0    0.0  26.6  0.351  31.0
2  8.0  183.0    0.0  23.3  0.672  32.0
3  1.0   89.0   94.0  28.1  0.167  21.0
4  0.0  137.0  168.0  43.1  2.288  33.0

In [44]:
selected_features = get_selected_features(X, X_new)

Pregnancies
Glucose
Insulin
BMI
DiabetesPedigreeFunction
Age


In [45]:
ANOVA_features = X[selected_features]
ANOVA_features.head()

Pregnancies  Glucose  Insulin   BMI  DiabetesPedigreeFunction   Age
0          6.0    148.0      0.0  33.6                     0.627  50.0
1          1.0     85.0      0.0  26.6                     0.351  31.0
2          8.0    183.0      0.0  23.3                     0.672  32.0
3          1.0     89.0     94.0  28.1                     0.167  21.0
4          0.0    137.0    168.0  43.1                     2.288  33.0

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [70]:
def build_model(x, y, frac):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=frac)
    model = LogisticRegression(solver='liblinear').fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print('Test score: ', accuracy_score(y_test, y_pred))

In [71]:
build_model(X, Y, 0.2)

Test score:  0.7532467532467533


In [72]:
build_model(chi2_features, Y, 0.2)

Test score:  0.7272727272727273


In [73]:
build_model(ANOVA_features, Y, 0.2)

Test score:  0.7792207792207793
